### PR TITLE
Added to the windows getting started page information about updating …

### PR DESCRIPTION
**Pull request by jashook**
Just one line of documentation change. This also marks a test on how to contribute to the repository and my first contribution.

### CODE REVIEW

**Comment by pgavlin** [comment]
Change looks good. Could you amend the commit message so that it matches the format below?

```
Commit Title

Summary of the change
```

For example:

```
Update the Windows Getting Started guide.

Add an instruction to install Visual Studio Update 4.
```

You can change the commit message by running `git commit --amend`, after which you'll need to force push to your fork with `git push --force [remote name] [branch name]` (since you've change the commit hash).

**Comment by jashook** [comment]
Thanks! how does that look?

**Comment by pgavlin** [comment]
LGTM.

**Comment by pgavlin** [comment]
The CI failure is unrelated; I'm going to go ahead and merge this.

**Pull request merged**
