### PR TITLE
Remove implicit list iterator conversions

### PR DESCRIPTION
**Pull request by JosephTremoulet**
LLVM change r252372 (git commit 84cb8974b) removed the implicit
conversions between ilist/iplist iterators and pointers to the iterated
nodes (to force people to consider whether they might be trying to
illegally cast an end iterator to a node).  Update LLILC sources to match.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
This will be needed to get the FI at Microsoft/llvm#114 to succeed.

**Comment by JosephTremoulet** [comment]
@AndyAyersMS PTAL

**Comment by AndyAyersMS** [comment]
LGTM.

**Comment by JosephTremoulet** [comment]
Failure is just the known unrelated issue with the new StructABI test; merging

**Pull request merged**
