### PR TITLE
Implement Array_GetDimLength intrinsic.

### LINKED ISSUE #561: Implement GenIR::arrayGetDimLength

### PR DESCRIPTION
**Pull request by erozenfeld**
The intrinsic returns the length of the specified dimension
for a vector or a multidimensional array.

Closes #561.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@AndyAyersMS PTAL

**Comment by AndyAyersMS** [comment]
LGTM

**Comment by erozenfeld** [comment]
retest this please

**Comment by erozenfeld** [comment]
retest this please

**Comment by erozenfeld** [comment]
Failures are unrelated. Merging now.

**Pull request merged**
