### PR TITLE
Ending Section to Ensure Section Symbols

### PR DESCRIPTION
**Pull request by kyulee1**
- Record sections that is used and endSection to ensure Section symbol creations.
- Register all executable sections to Dwarf sections so that debug info is created for them.

### CODE REVIEW

**Comment by kyulee1** [comment]
@janvorli @AndyAyersMS PTAL

**Comment by kyulee1** [comment]
@mmitche It appears all lab tests are failing. Any idea?

**Comment by janvorli** [comment]
LGTM, I've verified it fixes the problem with multiple executable sections on Linux that I was hitting in CoreRT.

**Comment by AndyAyersMS** [comment]
LGTM too. 

Are we using clang-format on this code? Just curious about the reformatting....

**Comment by kyulee1** [comment]
I used "ccformat --untidy". I think the format change is because the previous checkin didn't run it.

**Pull request merged**
