### PR TITLE
Disable fast ISel.

### PR DESCRIPTION
**Pull request by pgavlin**
The current implementation of the GC statepoint design is incompatible
with fast ISel, which may visit a call to @llvm.experimental.gc_result
before the corresponding call to @llvm.experimental.gc_statepoint.
Unfortunately, disabling fast ISel turns out not to be as simple as
setting TargetOptions.EnableFastISel to false; instead, the command-line
option must be set to 'false'.

### CODE REVIEW

**Comment by pgavlin** [comment]
@swaroop-sridhar @AndyAyersMS PTAL

**Comment by swaroop-sridhar** [comment]
Looks like this behavior changed recently?

I had watched the Jit take the the normal Isel path after setting TargetOptions.EnableFastISel= false.

**Comment by swaroop-sridhar** [comment]
The change is green for me.

**Comment by pgavlin** [comment]
@swaroop-sridhar I don't think that anything changed in LLVM. The relevant logic is here: https://github.com/Microsoft/llvm/blob/master/lib/CodeGen/LLVMTargetMachine.cpp#L126-L130

What I believe happened is that we started triggering the RHS of the condition.

**Comment by AndyAyersMS** [comment]
It seems odd that the only way to enforce this is via command line options parsing, but that appears to be the case.

LGTM too.

**Comment by pgavlin** [comment]
Build failure is due to #524; merging.

**Pull request merged**
