### PR TITLE
Add dummy predecessors for exception handlers

### PR DESCRIPTION
**Pull request by JosephTremoulet**
This will ensure that we know the incoming stack has an exception on it
when we first process the code in the handler.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@richardlford PTAL.  This should help with #636.

**Comment by richardlford** [comment]
I'm starting to review.

**Comment by richardlford** [comment]
@JosephTremoulet, LGTM.

**Comment by richardlford** [comment]
@JosephTremoulet, I'm going to go ahead and merge this so I can start building on it.

**Pull request merged**
