### PR TITLE
Update excludes to handle some renamed and adjusted tests

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Recent CoreCLR changes added different build flavors, update excludes accordingly.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@richardlford (or anyone) PTAL. I'll probably merge w/o review if CI is green.

**Comment by AndyAyersMS** [comment]
Fixed typo in one of the excludes, and a formatting issue.

**Comment by AndyAyersMS** [comment]
Pretty sure this is good, so am going to merge so we have good nightlies.

**Comment by richardlford** [comment]
@AndyAyersMS, looks good to me. Thanks for doing this.

**Pull request merged**
