### PR TITLE
Fix a warning and enable warnings as errors.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Fix a C4189 that I introduced recently. Turn on -WX for Windows builds for the code we author.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@JosephTremoulet I think you asked for this, so PTAL.

**Comment by JosephTremoulet** [comment]
1. Looks from the lab job like we have some additional warnings in release builds. @erozenfeld, were you looking into those?
2. One of the release warnings is coming from the gcencoder files we import from CoreCLR.  I think @swaroop-sridhar has PRed changes there to get rid of warnings in LLILC before, and we can do the same again here, but if we're going to keep getting breaks like this I wonder if maybe it wouldn't be prudent to build with warnings-as-errors after all (until/unless we do something along the lines of #543)
3. I don't know what's the difference between setting LLVM_ENABLE_WERROR=ON versus directly appending -WX, but I'd imagine we may want the former.

**Comment by AndyAyersMS** [comment]
I'm reluctant to turn on warning-as-error more broadly unless we're sure everyone who works on LLILC has the ability to repro the non-windows builds easily.

**Comment by JosephTremoulet** [comment]
My comment about LLVM_ENABLE_WERROR was intended as a question about the mechanism, not the policy. I'd imagine there's some way in cmake to set LLVM_ENABLE_WERROR conditionally based on the host platform, no? Are we sure that setting -WX where you set it has the same effect, or is it possible that using LLVM_ENABLE_WERROR would also pull in some -Wds, or affect only a subset of the compiler invocations, or set some preprocessor symbol, or etc.?

**Comment by AndyAyersMS** [comment]
Well, this question is answerable -- as of right now, (per LLVM sources)[https://github.com/Microsoft/llvm/blob/master/cmake/modules/HandleLLVMOptions.cmake], if warnings are enabled, `LLVM_ENABLE_WERROR` turns on `-Wx` for windows, and `-Werror` for "gcc compatible" compilers. So we could instead use `LLVM_ENABLE_WERROR` conditionally for windows to limit the scope of the error checks. It wouldn't change the behavior we see with just turning on `-Wx`.

**Comment by AndyAyersMS** [comment]
@erozenfeld @JosephTremoulet I'll fix the errors in LLILC... did we ever settle on which `#defines` we want to use for debug vs release?

**Comment by JosephTremoulet** [comment]
To me it seems like a kind of "layering violation" to use `-WX` directly, but feel free to ignore me if you think that's silly.  The only other thought I have about it is that I don't know if implementing it via `LLVM_ENABLE_WERROR` could make it easier for someone to override it on their cmake invocation, which could be desirable.

So LGTM modulo fixing the release warnings (or limiting this to just warn-as-error in debug builds), and fixing or excluding the imported CoreCLR sources.

**Comment by JosephTremoulet** [comment]
> did we ever settle on which #defines we want to use for debug vs release?

I didn't know there was an issue there, what are the alternatives?  I thought `NDEBUG` #defined for release and undefined for debug was the only option.

**Comment by AndyAyersMS** [comment]
I've switched over to using `LLVM_ENABLE_WERROR`. 

As far as conditional code: for "debug" only code we'd use `#ifndef NDEBUG`, right? Note we have a similar `NODEBUG` lurking about (as well as `_DEBUG`, etc).

**Comment by JosephTremoulet** [comment]
Right, `#ifndef NDEBUG` for debug-only code.  At least that's what I've been using, based on what LLVM does.

**Comment by AndyAyersMS** [comment]
I have what I hope is a full set of fixes locally, though annoyingly I can't repro some of the lab warnings in my local builds. It's obvious what needs to be fixed though, so this isn't blocking.

Waiting for related LLVM/CoreClr fixes to go in before pushing the LLILC part up.

**Comment by AndyAyersMS** [comment]
Ok, @JosephTremoulet, take another look. I updated the way we enable warnings as errors, and fixed all the warnings (I hope).

**Comment by JosephTremoulet** [comment]
LGTM, thanks for fixing this!

**Comment by AndyAyersMS** [comment]
Argh -- auditing the build lab logs, `set(LLVM_ENABLE_WERROR true)` is not effective. Need to redo this with something like `set(LLVM_ENABLE_WERROR ON)`.

**Comment by AndyAyersMS** [comment]
@JosephTremoulet had to backtrack to really get -WX through cmake. What I have now is similar to how we forcibly enable `-pedantic` for GCC, even if LLVM is not set up that way.

**Comment by JosephTremoulet** [comment]
Thanks, sorry for the headache.  I do like how the MSVC flags are now conditional on MSVC and not on WIN32, at least.

Looks good to me.

**Comment by AndyAyersMS** [comment]
Fixed a second-order effect....

**Comment by JosephTremoulet** [comment]
Still green :)

**Comment by erozenfeld** [comment]
LGTM too. Glad to see these treated as errors.

**Pull request merged**
