### PR TITLE
Fix exlusion.targets

### PR DESCRIPTION
**Pull request by swaroop-sridhar**
Include a test that is now passing.
Fix the issue reference for a few other bugs.

### CODE REVIEW

**Comment by swaroop-sridhar** [comment]
@richardlford: please review.

**Comment by swaroop-sridhar** [comment]
@dotnet-bot  test this

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test this please

**Comment by richardlford** [comment]
Changes look fine to me provided testing passes.

**Pull request merged**
