### PR TITLE
Refactoring Line Number Emission for CV

### PR DESCRIPTION
**Pull request by kyulee1**
This replaces the custom debug live emission code by CV line directives
that LLVM supports.
It also introduces Function/Module debug emission layers for the upcoming
work.

### CODE REVIEW

**Comment by kyulee1** [comment]
@AndyAyersMS @hoyMS PTAL

**Comment by russellhadley** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
LGTM too

**Comment by hoyMS** [comment]
LGTM

**Pull request merged**
