### PR TITLE
Add debug support for locals

### PR DESCRIPTION
**Pull request by adiaaida**
This change add support to LLILC to send local variable information to
LLVM and then on to the CLR EE to be used in debugging. This change
adds:

* Support to the Reader to capture local variables as they are created.
  We copy the logic from clang to specify if a local is a formal
  parameter or a regular local variable, though the CLR does not seem to
  care about this distinction. We assume that the local is in scope for
  the full function.
* Update convertType to deal with struct types. Since we don't use the
  type information for debugging, we can create a debug struct type with
  no real information about the struct. This change is really just there
  to prevent LLVM from attempting to reference a nullptr.
* Support to the ObjectLoadListener to extract DWARF information from
  the ObjectFile for local variables. Unlike line numbers, there is no
  built in support for extracting local variable information, so we have
  to add support to LLILC for this purpose. The extraction works much
  the same way as the DWARF info dumper: we extract the Unit
  DebugInfoEntry (DIE), find the Subprogram DIE -- DWARF's name for a
  function -- and then extract the locals that are in the subprogram.
  The DWARF format stores the frame_base register in the Subprogram
  DIE, so we must extract that and convert the DWARF register name to
  the value the CLR EE understands. Each of the locals can be found at
  an offset from the value in the frame_base register, and that offset
  is the last entry in the DW_AT_location attribute. For each local, we
  must then communicate back the EE the local number (assumed to be in
  order by creation in the DWARF info), the frame_base register and the
  offset. For now, we assume that all locals are found on the stack,
  though this may change, and will need future updates. If there were no
  locals in a function, we do not report anything back to the EE for
  that function.

### CODE REVIEW

**Comment by adiaaida** [comment]
@russellhadley PTAL

**Comment by adiaaida** [comment]
Please note: if this goes in before the LLVM FI, then we will need to update the reader to use createParameterVariable and createAutoVariable. If the FI goes in first, this change will need to be updated.

**Comment by adiaaida** [comment]
failed formatting. Updated in place.

**Comment by adiaaida** [comment]
updated to use the new functions for creating local variables for debug info.

**Comment by russellhadley** [comment]
Green.

**Comment by adiaaida** [comment]
This closes #593

**Pull request merged**
