### PR TITLE
Use CoreDisTools header from CoreCLR tree.

### PR DESCRIPTION
**Pull request by swaroop-sridhar**
The CoreDisTools header is now published by CoreCLR
Use that interface specification in building the
CoreDisTools library.

### CODE REVIEW

**Comment by swaroop-sridhar** [comment]
This change depends on https://github.com/dotnet/coreclr/pull/3874

**Comment by swaroop-sridhar** [comment]
@RussKeldorph please review

**Comment by swaroop-sridhar** [comment]
CC @AndyAyersMS

**Comment by RussKeldorph** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
LGTM too....

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test his please

**Comment by swaroop-sridhar** [comment]
This change depends on https://github.com/dotnet/coreclr/commit/4472a2285298d932cf01a902c44f5379bc2d4338 

So, I've restarted the testing

**Comment by swaroop-sridhar** [comment]
Merging the changeset since I;ve tested locally, and LLILC build will break otherwise (since the CoreCLR part is already checked in).

**Pull request merged**
