### PR TITLE
Exclude Regression\CLR-x86-JIT test cases that have issues with LLILC

### PR DESCRIPTION
**Pull request by libengu**
PR dotnet/coreclr#1120 added all remaining JIT\Regression test case. All under CLR-x86-JIT.
101 test cases have issue if run with LLILC. Exclude them. Issue https://github.com/dotnet/llilc/issues/628 is created for
investigation.

 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b28042\b28042
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b36471\b36471
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b48797\b48797
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b42929\b42929
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b73921\b73921
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b41391\b41391
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b83690\b83690
 JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b91917\b91917
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b37608\b37608
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b36274\b36274
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b40521\b40521
 JIT\Regression\CLR-x86-JIT\V1-M14-SP1\b119538\b119538b
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b60723\b60723
 JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b321799\repro
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b51463\b51463
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b46641\b46641
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b42918\b42918
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b49717\b49717
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b28037\b28037
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b56149\b56149
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b68634\b68634
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b32345\b32345
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b62555\b62555
 JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b89946\b89946
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b48929\b48929
 JIT\Regression\CLR-x86-JIT\V1-M10\b08944\b08944a
 JIT\Regression\CLR-x86-JIT\V1.2-M01\b02345\b02345
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b39217\b39217
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b31878\b31878
 JIT\Regression\CLR-x86-JIT\v2.1\DDB\b158861\b158861
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b51875\b51875
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b41470\b41470
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b43958\b43958
 JIT\Regression\CLR-x86-JIT\V1.2-M01\b16386\gtnop
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b28787\b28787
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b42013\b42013
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b27824\b27824
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b30128\b30128
 JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b92568\b92568
 JIT\Regression\CLR-x86-JIT\V1.2-M02\b00719\b00719
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b31917\b31917
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b72136\b72136
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b41621\b41621
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b52578\b52578
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b40496\b40496
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b41063\b41063
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b82866\b82866
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b48805\b48805
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b31903\b31903
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b11490\b11490
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b91377\b91377
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b41488\b41488
 JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b93027\b93027
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b30126\b30126
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b71120\b71120
 JIT\Regression\CLR-x86-JIT\v2.1\b106272\b106272
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b49318\b49318
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b40216\b40216
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b31763\b31763
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b40141\b40141
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b16328\b16328
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b52838\b52838
 JIT\Regression\CLR-x86-JIT\V1-M10\b08944\b08944
 JIT\Regression\CLR-x86-JIT\V1-M10\b08944\b08944b
 JIT\Regression\CLR-x86-JIT\V1.2-Beta1\b191926\ParamLimit
 JIT\Regression\CLR-x86-JIT\V1-M10\b05477\b05477
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b41495\b41495
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b49809\b49809
 JIT\Regression\CLR-x86-JIT\V1.2-M01\b16399\gtIsValid64RsltMul
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b77707\b77707
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b34945\b34945
 JIT\Regression\CLR-x86-JIT\V1.2-M01\b07900\rpPasses
 JIT\Regression\CLR-x86-JIT\v2.1\b602004\Inline_Vars2
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b32560\b32560
 JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b88797\b88797
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b55197\b55197
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b26863\b26863
 JIT\Regression\CLR-x86-JIT\v2.1\DDB\b33183\b33183
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b52746\b52746
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b47975\b47975
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b38556\b38556
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b16335\b16335
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b52572\b52572
 JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b91855\b91855
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b37131\b37131
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b30586\b30586
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b80045\b80045
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b71099\b71099
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b31182\b31182
 JIT\Regression\CLR-x86-JIT\v2.1\b152292\b152292
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b77713\b77713
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b51469\b51469
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b51565\b51565
 JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b62498\b62498
 JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b89277\b89277
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b43313\b43313
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b28776\b28776
 JIT\Regression\CLR-x86-JIT\V1-M14-SP1\b119538\b119538a
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b27819\b27819
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b36332\b36332
 JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b12624\b12624
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b43719\b43719

### CODE REVIEW

**Comment by libengu** [comment]
@AndyAyersMS @pgavlin PTAL

**Comment by AndyAyersMS** [comment]
Well, that's a depressingly high number of exclusions.

LGTM I suppose (doesn't really look good, but it's a necessary step).

Can you see if there's some quick way to determine if a test throws an exception? I know you can see it under the debugger but maybe there's some other cheap way -- eg turn on the summary trace and if we see the constructor for `System.Exception` being jitted, that's a pretty good sign that a throw is imminent.

**Comment by libengu** [comment]
Sure. I found I did not use issue number 628 in the change. I will run through it again to pick things that is easy to determine. The rest will default to issue number 628.

**Comment by libengu** [comment]
Looks like most of them are EH related.

**Comment by libengu** [comment]
We actually don't need to turn on summary trace. If it is due to EH, the dump out on screen will tell us.
We need to have more than 10 runs of llilc_runtest to exhaust to find it out.

**Comment by libengu** [comment]
Some are not EH related and cannot quickly identify. I will default to 628.

**Comment by AndyAyersMS** [comment]
So long as you can distinguish between (a) test throws an exception when jitted by both RyuJit and LLILC; and (b) test throws an exception only when jitted by LLILC, I'm fine with whatever technique you come up with. (a) is a test we can't handle yet; (b) is a bug in LLILC.

**Comment by libengu** [comment]
All the tests added passed RyuJit.

**Comment by libengu** [comment]
JIT\Regression\CLR-x86-JIT\V1.2-M02\b00719\b00719 was not added into CoreCLR. So it should be not in this exclusion list also.

**Comment by AndyAyersMS** [comment]
The fact that the test passes with RyuJit isn't very useful in determining the right classification for LLILC.

You need to figure out whether the LLILC-jitted verison fails for a known reason (LLILC jitted code can't catch exceptions) or some new reason. If you run the test with LLILC and you see an exception thrown you still don't know which case you're seeing -- if only if you see that same exception with RyuJit can you be fairly certain that the exception is expected behavior.

**Comment by libengu** [comment]
The dump contains some stack trace. Every test case is an exception throw. But some trace failed with UnwindStack something. I think it is due to LLILC EH not implemented. There are some test case with IL_Throw. I believe it is due to incorrect lowering to LLVM. I will try the summary thing.

**Comment by JosephTremoulet** [comment]
If it would help, we could consider translating MSIL `throw` instructions to FailFast (the runtime exposes a jit helper for that) instead of calling the throw helper, maybe under a switch.

**Comment by libengu** [comment]
I think what Andy said is effective to identify test case failed due to EH. Looking at summary trace for whether System.Exception related methods are jitted or not.

**Comment by libengu** [comment]
In both kinds of stack trace either IL_Throw or UnwindStack, the constructor of System.Exception is jitted.

**Comment by AndyAyersMS** [comment]
@libengu just checking -- do you plan to update the exclusion issue numbers before you merge this?

**Comment by libengu** [comment]
Yes.

**Comment by AndyAyersMS** [comment]
LGTM, thanks for investigating and updating the issue numbers.

**Pull request merged**
