### PR TITLE
Linux Comdat section support

### PR DESCRIPTION
**Pull request by nattress**
* Enable shared data between Elf object files by creating section groups for the shared comdat data to live in

### CODE REVIEW

**Comment by nattress** [comment]
@AndyAyersMS @sandreenko PTAL. This change is needed for the CoreRT sister commit https://github.com/nattress/corert/commit/ac078d04c6d483801771279a316b0e36d32f9fe7

**Comment by AndyAyersMS** [comment]
LGTM

**Comment by nattress** [comment]
I updated the Nuget packages for ObjectWriter to 1.0.15. Please merge this as I don't have write access to the repo.

**Comment by AndyAyersMS** [comment]
Done.

**Pull request merged**
