### PR TITLE
Add excludes for new and refactored tests

### LINKED ISSUE #967: Investigate failures from new tests
Lots of tests added to CoreCLR yesterday.

[18 tests failed](http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_ngen_check_win64/161/#showFailuresLink) in the nightly crossgen tests.

Suspect these also fail w/o crossgen, but we don't seem to run that leg unless there are commits to LLILC.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
All these require EH. All but one pass with ExecuteHandlers set.

Closes #967.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@richardlford PTAL

**Comment by richardlford** [comment]
@AndyAyersMS, LGTM.

**Comment by AndyAyersMS** [comment]
Missed a few, so pushed an update.

**Comment by AndyAyersMS** [comment]
Two more falures (`methodical\refany\*stress3`) with a check build. Excluding those as EH related for now.

**Comment by AndyAyersMS** [comment]
Am going to merge this eagerly in anticipation of clean nightly runs.

**Pull request merged**
