### PR TITLE
Refactor GenIR's constructor

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Some simple refactoring in anticipation of a further derived class that is specialized to read inlinees.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@pgavlin PTAL

**Comment by russellhadley** [comment]
Not sure about the time out but the code looks good to me.

**Comment by AndyAyersMS** [comment]
Saw a similar timeout on the same test case with a different change. That test requires spinning up a lot of threads, so perhaps the CI machines were loaded down or something. Will give it another try.

@dotnet-bot retest this please

**Comment by pgavlin** [comment]
LGTM.

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest this please

**Pull request merged**
