### PR TITLE
Handle classes with no parent class.

### PR DESCRIPTION
**Pull request by pgavlin**
This arises in the case of types that are not present in metadata,
e.g. the type that contains unboxing stubs.

### CODE REVIEW

**Comment by pgavlin** [comment]
@erozenfeld @AndyAyersMS PTAL

**Comment by erozenfeld** [comment]
LGTM assuming these classes aren't supposed to have a vtable field.

**Comment by AndyAyersMS** [comment]
It would be nice to verify when there is no parent that the type is one of these special cases.

Do these types have any non-static fields? If not, then describing the layout won't really matter anyways.

**Comment by pgavlin** [comment]
These types do not have any fields, no.

The build failure is due to #524; merging.

**Pull request merged**
