### PR TITLE
Update to shared enums

### PR DESCRIPTION
**Pull request by JosephTremoulet**
LLVM change r257712 (13d3e2ec) removed some members from COFF.h's
CodeViewIdentifiers enumeration that were used in the asm printer,
replacing them with equivalent constants from enums that it moved from
llvm-readobj to a shared header.  Update LLILC to use the shared enums.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@kyulee1 PTAL.  This blocked the nightly FI of llvm into the MS fork, and will need to go in at the same time as a manual FI.

**Comment by JosephTremoulet** [comment]
http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_prtest/1389 has a test run pairing these changes with Microsoft/llvm#132.

**Comment by pgavlin** [comment]
LGTM.

**Comment by pgavlin** [comment]
Looks like one of the EH-related tests is failing, BTW.

**Comment by JosephTremoulet** [comment]
> Looks like one of the EH-related tests is failing, BTW.

Yeah, just opened #1005 & #1006.

**Pull request merged**
