### PR TITLE
Fix Windows Jobs and add Ubuntu jobs

### PR DESCRIPTION
**Pull request by adiaaida**
The python script is case sensitive on the build type. Change debug and
release to all lower case. Add the Ubuntu jobs for debug and release

### CODE REVIEW

**Comment by adiaaida** [comment]
The last PR had mistakes in it and I accidentally merged. This one is updated, and should be fixed.

**Comment by adiaaida** [comment]
@dotnet-bot test ci please

**Comment by adiaaida** [comment]
@russellhadley PTAL.

**Comment by adiaaida** [comment]
@jashook PTAL

**Comment by jashook** [comment]
Looks good to me

**Pull request merged**
