### PR TITLE
Fix the target triple for out-of-tree builds.

### PR DESCRIPTION
**Pull request by pgavlin**
LLVMConfig.cmake (which we use when building out-of-tree) sets
TARGET_TRIPLE instead of LLVM_DEFAULT_TARGET_TRIPLE. Work around this
by setting LLVM_DEFAULT_TARGET_TRIPLE to TARGET_TRIPLE when building
out-of-tree.

### CODE REVIEW

**Comment by pgavlin** [comment]
@AndyAyersMS PTAL

**Comment by AndyAyersMS** [comment]
LGTM.

**Comment by pgavlin** [comment]
@dotnet-bot retest this please

**Comment by pgavlin** [comment]
@dotnet-bot test this please

**Pull request merged**
