### PR TITLE
Correct main CMakeLists.txt file for standalone executables.

### LINKED ISSUE #459: Standalone configuration missing settings needed for driver
When configuring standalone LLILC (i.e. not contained in LLVM/tools)
and also adding a driver executable the cmake configuration failed
because LLVM_RUNTIME_OUTPUT_INTDIR and CMAKE_ARCHIVE_OUTPUT_DIRECTORY
were not set. Solution is to set them appropriately.

### PR DESCRIPTION
**Pull request by richardlford**
When configuring standalone LLILC (i.e. when the LLILC repo
is not placed in LLVM/tools), we were not setting
LLVM_RUNTIME_OUTPUT_INTDIR and LLVM_LIBRARY_OUTPUT_INTDIR.
These must be set if an executable is added.
Also added a dummy driver to verify that it is
compiled and executable created for it.

Closes #459.

### CODE REVIEW

**Comment by richardlford** [comment]
@pgavlin  PTAL.

**Comment by pgavlin** [comment]
CMake changes LGTM. @russellhadley for the rest.

**Comment by russellhadley** [comment]
Is this just to hold the build scripts together?  Seems odd to just add an empty main() that does nothing.

**Comment by richardlford** [comment]
As @russellhadley and I discussed, I added comments explaining that the llilc_aot.cpp file is a placeholder for what will eventually be the LLILC ahead-of-time compiler driver.

**Comment by kyulee1** [comment]
@richardlford Can you remove this empty main? I don't see much value except causing merge problem with prototyping.

**Comment by richardlford** [comment]
@kyulee1 I removed the placeholder driver and reverted the driver CMakeLists.txt to an empty file.

**Pull request merged**
