### PR TITLE
Print command line arguments passed to ccformat

### PR DESCRIPTION
**Pull request by adiaaida**
In the lab, we aren't seeing any output from ccformat. To confirm that
it is being run, we want to print out the command line arguments that
were passed to ccformat.py.

### CODE REVIEW

**Comment by adiaaida** [comment]
@swaroop-sridhar PTAL

This will print 

Running ccformat.py with: ['--fix']

if the command is
ccformat.py --fix

**Comment by swaroop-sridhar** [comment]
I think we should print the command line for both clang-tidy and clang-format -- just printing one is confusing.

The other option is to not print anything from within ccFormat -- but change the lab-job to just print the invocation of ccFormat. (No further output means success).

**Comment by adiaaida** [comment]
I tried to do the later. I could not get it to print out the invocation of ccformat.py. 

The only way I've been able to get it to run with printing ccformat's invocation is to do vcvarsall.bat && ccformat.py which I didn't want to do here in case we needed to do something after ccformat.

**Comment by swaroop-sridhar** [comment]
OK, then let's print a message for the invocation of both clang-tidy and clang-format then. For clang-tidy, since we do several invocations, we could just print "Running clang-tidy ... " or something like that once. [To ensure that I won't be confused later that it is not running]. Thanks.

**Comment by swaroop-sridhar** [comment]
Apart from the above comment, green for me. Thanks for fixing this.

**Comment by adiaaida** [comment]
Fixed in place. We now print "Running clang-tidy" and "Running clang-format" before running those steps.

**Pull request merged**
