### PR TITLE
Exclude failing HFA tests

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Still using blanket reason #970, need triage.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@JosephTremoulet PTAL

**Comment by AndyAyersMS** [comment]
Looks like there are some non-HFA failures from the chk build for #973 so this may need tweaking.

**Comment by AndyAyersMS** [comment]
Added four more excludes (none from HFA tests).

**Comment by JosephTremoulet** [comment]
LGTM

**Pull request merged**
