### PR TITLE
Fix ccFormat failures

### PR DESCRIPTION
**Pull request by swaroop-sridhar**
Fix the ccFormat failures with the latest build of
clang-format and clang-tidy tools.

This checkin depends on some renaming changes in LLVM.
https://github.com/Microsoft/llvm/pull/72

So, the lab tests will fail for this job until both changes are checked in at the same time.

### CODE REVIEW

**Comment by swaroop-sridhar** [comment]
@adiaaida please review

**Comment by swaroop-sridhar** [comment]
I've requested a build with parameters to test with both LLVM and LLILC changes:
http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_prtest/928/

**Comment by russellhadley** [comment]
LGTM

**Comment by adiaaida** [comment]
LGTM

**Comment by russellhadley** [comment]
@dotnet-bot retest this please

**Comment by mmitche** [comment]
@swaroop-sridhar @russellhadley I'm going to take down Jenkins for some maintenance and such.  I'll retest this job when done

**Comment by russellhadley** [comment]
@dotnet-bot retest this please

**Comment by adiaaida** [comment]
@dotnet-bot test this please

**Comment by adiaaida** [comment]
This change requires LLVM changes. We should watch this job Swaroop started: http://dotnet-ci.cloudapp.net/job/dotnet_llilc_prtest/932/

**Comment by swaroop-sridhar** [comment]
Yes, will check-in Llvm and Llilc changes together if the private PR job passes. Thanks.

**Comment by adiaaida** [comment]
I didn't have the job completely up-to-date. I've restarted the code formatting leg.

**Comment by adiaaida** [comment]
code formatting leg: http://dotnet-ci.cloudapp.net/job/dotnet_llilc_code_formatting_prtest/593

**Comment by swaroop-sridhar** [comment]
@adiaaida: this leg succeeded, but it doesn’t seem to call ccFormat?

code formatting leg: http://dotnet-ci.cloudapp.net/job/dotnet_llilc_code_formatting_prtest/593

**Comment by adiaaida** [comment]
It does call it, it just doesn't show up because we call vcvarsall.bat. Maybe we could update ccFormat to print something out on successful run. I can work on that.

LGTM

**Comment by swaroop-sridhar** [comment]
OK Thanks @adiaaida -- would be good enough if we print the call to ccFormat in the logs. Thanks.

**Comment by adiaaida** [comment]
Yeah. I'll look into it

**Pull request merged**
